[[constraint]]
  name = "github.com/ethereum/go-ethereum"
  # TODO: Remove this forked source and branch once Turbo-Geth is ready as a
  # client.
  source = "github.com/alexanderbez/go-ethereum"
  branch = "ethermint-statedb"

[[constraint]]
  name = "github.com/cosmos/cosmos-sdk"
  revision = "ec9c4ea543b5d0f558cf6ad9f1386d26cfe87f28"
  # version = "v0.28.0"

[[constraint]]
  name = "github.com/hashicorp/golang-lru"
  revision = "0fb14efe8c47ae851c0034ed7a448854d3d34cf3"

[[constraint]]
  name = "github.com/spf13/cobra"
  version = "~0.0.1"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "=1.2.1"

[[constraint]] 
  name = "github.com/pkg/errors"
  version = "=0.8.0"

[[constraint]]
  name = "golang.org/x/net"
  revision = "292b43bbf7cb8d35ddf40f8d5100ef3837cced3f"

#######################
# dependecy overrides #
#######################

[[override]]
  name = "gopkg.in/fatih/set.v0"
  version = "=0.1.0"

[[override]]
  name = "github.com/tendermint/go-amino"
  version = "v0.14.1"

[[override]]
  name = "golang.org/x/crypto"
  source = "https://github.com/tendermint/crypto"
  revision = "3764759f34a542a3aef74d6b02e35be7ab893bba"

[[override]]
  name = "github.com/tendermint/iavl"
  version = "v0.12.0"

[[override]]
  name = "github.com/tendermint/tendermint"
  revision = "v0.27.0"

[[override]]
  name = "golang.org/x/sys"
  revision = "4e1fef5609515ec7a2cee7b5de30ba6d9b438cbf"

[prune]
  go-tests = true
